//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../proxy';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../proxy';
import { getAxios, getBaseUrl } from './helpers';

/**
 * @return Success
 */
export function bookDELETE(id: string, config?: AxiosRequestConfig | undefined): Promise<string> {
    let url_ = getBaseUrl() + "/api/Book/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigBookDELETE,
        ...config,
        method: "DELETE",
        url: url_,
        headers: {
            ..._requestConfigBookDELETE?.headers,
            "Accept": "text/plain"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processBookDELETE(_response);
    });
}

function processBookDELETE(response: AxiosResponse): Promise<string> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = JSON.parse(resultData200);
        return Promise.resolve<string>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<string>(null as any);
}

/**
 * @return Success
 */
export function bookAll(config?: AxiosRequestConfig | undefined): Promise<Types.BookDto[]> {
    let url_ = getBaseUrl() + "/api/Book";
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigBookAll,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigBookAll?.headers,
            "Accept": "text/plain"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processBookAll(_response);
    });
}

function processBookAll(response: AxiosResponse): Promise<Types.BookDto[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = JSON.parse(resultData200);
        return Promise.resolve<Types.BookDto[]>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.BookDto[]>(null as any);
}

/**
 * @param body (optional) 
 * @return Success
 */
export function bookPOST(body?: Types.BookInput | undefined, config?: AxiosRequestConfig | undefined): Promise<Types.BookDto> {
    let url_ = getBaseUrl() + "/api/Book";
      url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
        ..._requestConfigBookPOST,
        ...config,
        data: content_,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigBookPOST?.headers,
            "Content-Type": "application/json",
            "Accept": "text/plain"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processBookPOST(_response);
    });
}

function processBookPOST(response: AxiosResponse): Promise<Types.BookDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = JSON.parse(resultData200);
        return Promise.resolve<Types.BookDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.BookDto>(null as any);
}
let _requestConfigBookDELETE: Partial<AxiosRequestConfig> | null;
export function getBookDELETERequestConfig() {
  return _requestConfigBookDELETE;
}
export function setBookDELETERequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigBookDELETE = value;
}
export function patchBookDELETERequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigBookDELETE = patch(_requestConfigBookDELETE ?? {});
}

let _requestConfigBookAll: Partial<AxiosRequestConfig> | null;
export function getBookAllRequestConfig() {
  return _requestConfigBookAll;
}
export function setBookAllRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigBookAll = value;
}
export function patchBookAllRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigBookAll = patch(_requestConfigBookAll ?? {});
}

let _requestConfigBookPOST: Partial<AxiosRequestConfig> | null;
export function getBookPOSTRequestConfig() {
  return _requestConfigBookPOST;
}
export function setBookPOSTRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigBookPOST = value;
}
export function patchBookPOSTRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigBookPOST = patch(_requestConfigBookPOST ?? {});
}